### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mafftor** [mafftor/laravel-file-manager#1]
## TODO:
* [x] Cloud improvements and optimizations.
* [ ] Add subfolders for tree.
* [ ] Context menu (Right click menu)
* [ ] Add manager type switcher (files, images)
* [ ] Front to React + Redesign.
* [ ] Create demo.
* [ ] README improvements
